version: '3.8'

services: 
  worksy-server:
    container_name: worksy-server
    image: worksy4350/worksy-server:latest
    build: 
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  worksy-client: 
    container_name: worksy-client
    image: worksy4350/worksy-client:latest
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - 3030:3030

