name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Build and push Docker image
        if: github.event.pull_request.merged == true
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t your-docker-image-name:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker tag your-docker-image-name:latest your-dockerhub-username/your-docker-image-name:latest
          docker push your-dockerhub-username/your-docker-image-name:latest

      - name: Deploy to Docker container
        run: |
          # Pull the latest Docker image and restart the container
          docker pull your-dockerhub-username/your-docker-image-name:latest
          docker stop your-container-name
          docker rm your-container-name
          docker run -d --name your-container-name -p 80:80 your-dockerhub-username/your-docker-image-name:latest

